---
title: "Publications"
freeze: true
format: html
---

# 2021

Kellie, D. J., Blake, K. R., & Brooks, R. C. (2021). **Prejudice towards sex workers depends on the sexual activity and autonomy of their work, hobbies and daily activities.** *Collabra: Psychology*, *7*(1), 24386.  [https://doi.org/10.1525/collabra.24386](https://doi.org/10.1525/collabra.24386) 
*This paper is open access!*
[Preprint on Psyarxiv](https://doi.org/10.31234/osf.io/zu8q5)

Kellie, D. J., Blake, K. R., & Brooks, R. C. (2021). **Behind the makeup: The effects of cosmetics on women's self‐objectification, and their objectification by others**. *European Journal of Social Psychology*. [https://doi.org/10.1002/ejsp.2767](https://doi.org/10.1002/ejsp.2767)  
[Prepint on Psyarxiv](https://psyarxiv.com/6uy7z)

# 2020

Kellie, D. J., Dixson, B., & Brooks, R. (2020). **Papa don’t preach? Using lies to expose the truth about who suppresses female sexuality**. *Human Nature*, 1-27. [https://doi.org/10.1007/s12110-020-09372-7](https://doi.org/10.1007/s12110-020-09372-7)

# 2019

Kellie, D. J., Blake, K. R., & Brooks, R. (2019). **What drives female objectification? An investigation of appearance-based interpersonal perceptions and the objectification of women**. *PLoS One*, *14*(8), e0221388. [https://doi.org/10.1371/journal.pone.022138830](https://doi.org/10.1371/journal.pone.022138830)  
[UNSW 3 Minute Thesis talk on this paper](https://www.youtube.com/watch?v=2f6GijzMCSU)

# Preprints

Kellie, D. J., Parker, T., & Nakagawa, S. (in prep). To what extent do biological and methodological differences drive heterogeneity in results in ecology?  
*Pre-registration available on the* [Open Science Framework](https://osf.io/n36sx/?view_only=39ab7cd386ba49b0b723fd09fefe3b5d)

