---
title: "Writings"
subtitle: "Articles I've written in other places"
format: 
  html: 
    css: theme.css
title-block-banner: "#C6732F"
title-block-banner-color: "#ffffff"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r, include=FALSE}
library(htmltools)
source("R/functions.R")
```

## Blogs

::: {.column-body-outset}

::: {.grid}
::: {.g-col-4}

```{r}
create_writings_image(
  img_src = "writings/images/nature-blog.avif",
  url = "https://ecoevocommunity.nature.com/posts/improving-code-reproducibility-small-steps-with-big-impacts"
)
```

:::
::: {.g-col-8}
[**Improving code reproducibility: Small steps with big impacts**](https://ecoevocommunity.nature.com/posts/improving-code-reproducibility-small-steps-with-big-impacts) \
Blog post for Nature Ecology & Evolution Community \
[*July 2023*]{style="font-size:.8rem"}
:::
:::
:::

## Tutorials

::: {.column-body-outset}

::: {.grid}
::: {.g-col-4}

```{r}
create_writings_image(
  img_src = "writings/images/raincloud.png",
  url = "https://labs.ala.org.au/posts/2023-08-28_alternatives-to-box-plots/post.html"
)
```

:::
::: {.g-col-8}
[**Alternatives to box plots: Using beeswarm and raincloud plots to summarise ecological data}**](https://labs.ala.org.au/posts/2023-08-28_alternatives-to-box-plots/post.html) \
Post for ALA Labs \
[*August 2023*]{style="font-size:.8rem"}
:::

::: {.g-col-4}

```{r}
create_writings_image(
  img_src = "writings/images/samplebias.png",
  url = "https://labs.ala.org.au/posts/2022-07-22_sample-bias/post.html"
)
```

:::
::: {.g-col-8}
[**Quantify geographic sampling bias with {sampbias}**](https://labs.ala.org.au/posts/2022-07-22_sample-bias/post.html) \
Post for ALA Labs \
[*August 2022*]{style="font-size:.8rem"}
:::

::: {.g-col-4}

```{r}
create_writings_image(
  img_src = "writings/images/map_plants-3d.png",
  url = "https://labs.ala.org.au/posts/2022-05-17_3d-map/post.html"
)
```

:::
::: {.g-col-8}
[**Download plant species data by hexagon to make a 3D hex map**](https://labs.ala.org.au/posts/2022-05-17_3d-map/post.html) \
Post for ALA Labs \
[*May 2022*]{style="font-size:.8rem"}
:::


:::
:::