project:
  type: website

website:
  title: "Dax Kellie"
  open-graph: true
  twitter-card:
    creator: "@daxkellie"
    card-style: summary_large_image
  background: light
  navbar:
    logo: images/favicon.ico
    background: "#f9feff"
    foreground: "#e4b48c"
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: publications.qmd
        text: Publications
      - href: blog.qmd
        text: Blog
      - href: music.qmd
        text: Music
      - href: https://twitter.com/daxkellie
        icon: twitter
      - href: https://github.com/daxkellie
        icon: github
  search: true
  

format:
  html:
    theme: 
      - yeti
      - custom_theme.scss
    css: theme.css
    toc: true



