---
title: "Portfolio"
subtitle: |
  Projects, packages, research & things I've written in other places
title-block-banner: "#F8EFE7"
title-block-banner-color: "#934C12"
format: 
  html:
    anchor-sections: false
    preview-links: true
---

```{r}
#| include: false
source("../R/functions.R")
library(htmltools)
```


::: {.column-page}

```{r}
#| echo: false
tags$div(class = "row",# Create a row for 3 team-member cards
         
create_portfolio_card(
  title = "ALA Labs",
  image = "images/ala-labs.png",
  url = "https://labs.ala.org.au/",
  description = "Atlas of Living Australia's website for coding solutions to scientific problems."
),
create_portfolio_card(
  title = "Improving code reproducibility: Small steps with big impacts",
  image = "images/nature-blog.avif",
  url = "https://ecoevocommunity.nature.com/posts/improving-code-reproducibility-small-steps-with-big-impacts",
  description = "Blog post for Nature Ecology & Evolution Community | July 2023"
),
create_portfolio_card(
  title = "Dataviz",
  image = "images/bats.png",
  url = "dataviz/index.html",
  description = "Visualisations made in R."
),
create_portfolio_card(
  title = "Packages",
  image = "images/galah_logo.png",
  url = "packages/index.html",
  description = "R packages for data science."
)
)
```

```{r}
#| echo: false
tags$div(class = "row",# Create a row for 3 team-member cards

create_portfolio_card(
  title = "Books",
  image = "images/cleaner-shrimp_cover.png",
  url = "books/index.html",
  description = "Long-form resources for data wrangling & analysis."
),
create_portfolio_card(
  title = "Publications",
  image = "images/fig3b_hexmap_frog.png",
  url = "publications/index.html",
  description = "Scientific publications, government reports and other articles."
),
create_portfolio_card(
  title = "Tutorials",
  image = "images/raincloud.png",
  url = "tutorials/index.html",
  description = "Articles to teach R & Python"
),
create_portfolio_card(
  title = "Art",
  image = "images/new_leaf.png",
  url = "art/index.html",
  description = "I dabble."
)
)
```

:::
